name: issue_to_notion
on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: github2notion
        uses: memew1se/github-to-notion@v0.3.0
        env:
          ASSIGNEES_PROPERTY_NAME: "Ответственный"
          BRACKET_TYPES: 4
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          DEBUGGING: true
          GITHUB2NOTION_PRIORITY: '{"name": "Приоритет", "object": {"select": {"name": "P3"}}}'
          GITHUB2NOTION_PROJECT: '{"name": "Проект", "object": {"select": {"name": "Olymp Group"}}}'
          GITHUB_ASSIGNEES_TO_NOTION: ${{ secrets.GITHUB_ASSIGNEES_TO_NOTION }}
          GITHUB_STATUSES_TO_NOTION: ${{ secrets.GITHUB_STATUSES_TO_NOTION }}
          LABELS_PROPERTY_NAME: "Вид"
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          STATUS_PROPERTY_NAME: "Статус"
          TITLE_PROPERTY_NAME: "Заголовок"
